before_script:
 - apk update
 - apk add make m4 ocaml perl build-base gcc zlib-dev ca-certificates wget opam patch sqlite-dev glib-dev pkgconfig gmp-dev ncurses-dev
 - update-ca-certificates
 - export OPAMYES=true
 - comp=${1:-system}
 - opam init --comp="${comp}"
 - eval `opam config env`
 - opam update
 - opam install camlp4
 - opam upgrade
 - ocaml -version
 - opam --version
 - camlp4 -version
 - opam install ocamlbuild cryptokit opium sqlexpr

build:
  script: "cd server && make"