before_script:
 - apk update
 - apk add make m4 ocaml perl build-base gcc zlib-dev
 - wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
 - export OPAMYES=true
 - comp=${1:-system}
 - opam init --comp="${comp}"
 - eval `opam config env`
 - opam install ocamlfind
 - opam install ocamlbuild tls cryptokit opium sqlexpr

build:
  script: "cd server && make"