before_script:
 - apk update
 - apk add make m4 opam perl build-base gcc abuild binutils
 - opam init
 - eval `opam config env`
 - opam install ocamlbuild tls cryptokit opium sqlexpr

build:
  script: "cd server && make"