before_script:
 - echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/community/" >> /etc/apk/repositories
 - cat /etc/apk/repositories
 - apk update
 - apk add make m4 ocaml perl build-base gcc zlib-dev ca-certificates wget opam@edge patch sqlite-dev glib-dev pkgconfig gmp-dev ncurses-dev camlp4=4.04-r0 git
 - update-ca-certificates
 - export OPAMYES=true
 - comp=${1:-system}
 - opam init --comp="${comp}"
 - eval `opam config env`
 - opam repo add janestreet https://github.com/janestreet/opam-repository.git
 - opam update
 - opam install ppx_ast || true
 - cat /root/.opam/system/build/ppx_ast.v0.9.0/ppx_ast-*.err
 - opam update
 - opam install camlp4
 - opam upgrade
 - ocaml -version
 - opam --version
 - camlp4 -version
 - opam install ocamlbuild cryptokit opium sqlexpr

build:
  script: "cd server && make"