before_script:
 - cat /etc/apk/repositories
 - echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main/" >> /etc/apk/repositories
 - apk update
 - apk add make m4 ocaml perl build-base gcc zlib-dev ca-certificates wget opam@edge patch sqlite-dev glib-dev pkgconfig gmp-dev ncurses-dev camlp4=4.04-r0
 - update-ca-certificates
 - export OPAMYES=true
 - comp=${1:-system}
 - opam init --comp="${comp}"
 - eval `opam config env`
 - opam update
 - opam install camlp4
 - opam upgrade
 - ocaml -version
 - opam --version
 - camlp4 -version
 - opam install ocamlbuild cryptokit opium sqlexpr

build:
  script: "cd server && make"